version = 1

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
plugins = ["vue"]

[[analyzers]]
name = "test-coverage"
enabled = true

exclude_patterns = [
  "stories/**"
]

test_patterns = [
  "src/tests/**",
  "*.test.js"
]
